# Generated by Django 5.2.1 on 2025-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=2)),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('work_wear', 'Work wear'), ('graduation', 'Graduation'), ('party', 'Party'), ('mini_dresses', 'Mini Dress'), ('maxi_dress', 'Maxi Dress'), ('knee_lenth_dress', 'Knee Length Dress'), ('crop_tops', 'Crop Tops'), ('bodysuits', 'BodySuits'), ('blouses', 'Blouses'), ('wrap_tops', 'Wrap Tops'), ('corsets', 'Corsets'), ('pants', 'Pants'), ('pants_sets', 'Pants Sets'), ('shorts', 'Shorts'), ('jackets', 'Jackets'), ('kimonos', 'Kimonos'), ('shawls', 'Shawls'), ('Cardigans', 'Cardigans'), ('jewelry', 'Jewelry'), ('belts', 'Belts'), ('sandals', 'Sandals')], default='occassion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
