# Generated by Django 5.2.1 on 2025-05-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
