# Generated by Django 5.2.1 on 2025-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_productcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('Dresses', 'dresses'), ('Pants_Sets', 'pants_sets'), ('Skirts', 'skirts'), ('Tops', 'tops')], default='occassion'),
        ),
    ]
