# Generated by Django 5.2.1 on 2025-06-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_productcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('dresses', 'Dresses'), ('pants_sets', 'Pants Sets'), ('skirts', 'Skirts'), ('tops', 'Tops')], default='occassion'),
        ),
    ]
