# Generated by Django 5.2.1 on 2025-08-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='selected_color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='selected_size',
        ),
    ]
