# Generated by Django 5.2.1 on 2026-06-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_order_stock_reduced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('dresses', 'Dresses'), ('pants_sets', 'Pants Sets'), ('skirts', 'Skirts'), ('tops', 'Tops')], default='dresses', max_length=20),
        ),
    ]
